apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-02-01T22:39:09Z"
  generation: 1
  labels:
    app: gxp-track-auditable-containerization-demo
  name: gxp-track-auditable-containerization-demo
  namespace: default
  resourceVersion: "19499"
  uid: 5ff5b3be-7ab7-4309-b9ed-fe4541577ecd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gxp-track-auditable-containerization-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gxp-track-auditable-containerization-demo
    spec:
      containers:
        - image: local.registry.idempotence.io/gxp-track-auditable-containerization-demo:latest
          imagePullPolicy: Always
          name: gxp-track-auditable-containerization-demo
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext:
            privileged: true
          volumeMounts:
            - name: containerd-storage
              mountPath: /var/lib/containerd
              mountPropagation: Bidirectional # Or Bidirectional if needed
      volumes:
        - emptyDir:
            medium: Memory # tmpfs storage
            sizeLimit: 200Mi # Restricting storage size
          name: tmpfs-storage
        - name: containerd-storage
          hostPath:
            path: /var/lib/containerd-containerized # Ensure this path exists on your nodes
            type: DirectoryOrCreate # Allows the directory to be created if absent
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
    - lastTransitionTime: "2025-02-01T22:39:09Z"
      lastUpdateTime: "2025-02-01T22:39:09Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2025-02-01T22:39:09Z"
      lastUpdateTime: "2025-02-01T22:39:09Z"
      message: ReplicaSet "gxp-track-auditable-containerization-demo-849f9b5bc6" is progressing.
      reason: ReplicaSetUpdated
      status: "True"
      type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
