# Generated by Django 3.2.9 on 2021-11-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_contact_email', models.EmailField(max_length=254)),
                ('company_contact_phone', models.CharField(max_length=200)),
                ('accounts_receivable_email', models.EmailField(max_length=254)),
                ('company_type', models.CharField(choices=[('SUPPLIER', 'Supplier'), ('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer')], default='SUPPLIER', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('interested_in_marketing_email', models.BooleanField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
    ]
